In [8]:
import pandas as pd

test_path = r'datasets/test.csv'
data_path = r'datasets/data.csv'

test = pd.read_csv(test_path)
data = pd.read_csv(data_path)

In [9]:
test.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2018-07-02,43.060001,45.000000,42.750000,44.980000,44.980000,16703600
1,2018-07-03,45.360001,45.480000,43.799999,43.889999,43.889999,14237500
2,2018-07-05,44.070000,45.110001,43.549999,45.060001,45.060001,16172000
3,2018-07-06,44.910000,46.750000,44.610001,46.650002,46.650002,23740700
4,2018-07-09,46.740002,46.900002,42.080002,44.139999,44.139999,107582400

In [10]:
data.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2018-07-02,183.820007,187.300003,183.419998,187.179993,182.199005,17731300
1,2018-07-03,187.789993,187.949997,183.539993,183.919998,179.025772,13954800
2,2018-07-05,185.259995,186.410004,184.279999,185.399994,180.466370,16604200
3,2018-07-06,185.419998,188.429993,185.199997,187.970001,182.967972,17485200
4,2018-07-09,189.500000,190.679993,189.300003,190.580002,185.508545,19756600